### ISSUE TITLE
Some more documentation

### ISSUE THREAD

**Issue by colincalnan** [256dpi/middleman-lunr#1]
Could you possibly provide some more documentation for this. Such as where you place the search.json.erb file, as well as where the Javascript ($.getJSON) goes and how this all integrates to create a search results page.

**Comment by 256dpi** [comment]
I updated the README to be more specific about where to put the files.

For the second part: This heavily depends on the individual use case. In most projects you want to preload the index after the page has been loaded. Then you could listen for "change" events on a text field, query the index and render the results somewhere on the page.

An example: https://docs.shiftr.io

**Comment by colincalnan** [comment]
Joel, thanks for the quick response, this is invaluable. I'll test it on Monday and get back to you. Much appreciated.

**Comment by 256dpi** [comment]
You'r welcome, i'll close the issue for now, but get back to me if you have more questions.

**Comment by colincalnan** [comment]
Joel, 

thanks for that, however there is something else that's missing from the documentation. You need to include the lunr.js in a script tag in your document, correct?

```
<script src="//cdnjs.cloudflare.com/ajax/libs/lunr.js/0.5.9/lunr.min.js" type="text/javascript"></script>
```

Now that I've done that I can hit `http://localhost:4567/search.json` however, it's not returning any data.

Here's the response:

```
{
  "index": {
    "version": "0.5.9",
    "fields": [
      {
        "name": "body",
        "boost": 1
      },
      {
        "name": "title",
        "boost": 1
      },
      {
        "name": "random",
        "boost": 1
      }
    ],
    "ref": "id",
    "documentStore": {
      "store": {},
      "length": 0
    },
    "tokenStore": {
      "root": {
        "docs": {}
      },
      "length": 0
    },
    "corpusTokens": [],
    "pipeline": [
      "trimmer",
      "stopWordFilter",
      "stemmer"
    ]
  },
  "map": {}
}
```

Here's my `search.json.erb`

```
<%= JSON.generate(generate_search_index({data: [:title, :random]})) %>
```

Here's an About Page

```
- @title = "About Us"
- @random = "The planet is spinning"

.layout--header
  .layout--header-inner
    %h3.sample  This is the About Page

.layout--content
  .layout--content-left
    .sample--content
      %h3#foo left
      Suspendisse lacinia nulla a mauris blandit convallis. Cras nisi tortor, tempus vel turpis auctor, semper malesuada lectus. Maecenas bibendum euismod tristique. Donec ultricies, tellus nec congue lacinia, dui nibh maximus odio, sed lacinia velit turpis a augue. Fusce interdum volutpat sapien. Quisque ut purus a dui laoreet tempus at tincidunt nulla. In sodales augue sed neque vestibulum, vel aliquam ipsum ullamcorper. Fusce at augue lorem. Integer at dui arcu. In vel venenatis libero. Maecenas ac ultrices elit.
      = link_to "Page 1", "/page-1.html"
```

What am I missing, It's not indexing!

I'm also running `bundle exec middleman` to get middleman running.

**Comment by 256dpi** [comment]
You need to mark the files that should be indexed:

```
index: true
```

In your case, I guess:

``` slim
- @index = true
```

Sorry for not pointing that out in the readme. I thought the extensions was self explanatory, but didn't remember that I added all that hidden stuff. ;)

**Comment by colincalnan** [comment]
Thanks, 

that makes sense, however that's not returning anything in the documentStore when I hit search.json, any other idea. I really appreciate the help, I'm new to Middleman and trying to determine if it's something I can use. 

Also, will this work with the i18n extension?

**Comment by 256dpi** [comment]
Would you be able to give me access to your code, so I could test some things?

I didn't try I18n stuff yet...

**Comment by colincalnan** [comment]
Joel,

I got it working.

the frontend matter was borked due to my “special” formatting. Works well
now. In regards to i18n, have started doing a little digging into that, and
will let you know what I find out.

For now, I’m good. thank you so much for being so responsive in your
support.

**Comment by 256dpi** [comment]
Nice! Finally. ;)

You're welcome!
