### ISSUE TITLE
Error: 'nesting of 100 is too deep' when running build

### ISSUE THREAD

**Issue by colincalnan** [256dpi/middleman-lunr#2]
Joel, 

I'm getting the following error when running `middleman build`    

```
== Request: /search.json
       error  build/search.json
nesting of 100 is too deep
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:223:in `generate'
```

Apparently I can change this using `:max_nesting => false` or a number higher than 100.

I have tried to do this in `indexer.rb` link 61

`data = JSON.parse(idx.dumpIndex(), :max_nesting => 300)`

But it's not working. I'm not very familiar with gems, do I need to reload locally?

**Comment by 256dpi** [comment]
Hi Colin

I don't know your setup. Normally, you would clone this repository or your fork in another directory and then require the changed gem in your Gemfile:

``` ruby
gem 'middleman-lunr', path: '/some/path/middleman-lunr'
```

About the problem:
In never ran into this situation, can you tell more about your project, and what you are indexing?

**Comment by monfresh** [comment]
I'm running into this as well. I am indexing the title, tags, date, category_title, and category for each post. I have 583 posts, and setting `max_nesting: 1000` did not help.

**Comment by monfresh** [comment]
The issue is most likely related to the number of posts that need to be indexed because if I only specify `index: true` for 2 posts, this error does not occur. Given this fact, the issue is most likely in the indexer code. It is nesting JSON too deeply somewhere.

**Comment by 256dpi** [comment]
Others have the same problem too:
https://github.com/slashdotdash/jekyll-lunr-js-search/pull/60/files

Someone has time to do a PR as I'm very busy atm?

**Comment by monfresh** [comment]
I fixed this and will send a PR soon.

**Comment by 256dpi** [comment]
The option `max_nesting` is set to `false` in latest version.
